steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --pull
      - --file
      - cloud/google_batch/Dockerfile
      - --tag
      - ${_IMAGE_URI}
      - .
images:
  - ${_IMAGE_URI}
